services:
  app:
    volumes:
      - type: bind
        source: ./src
        target: /srv/shiny-proteomics/src
    entrypoint: /bin/bash
    container_name: shiny-dev
    stdin_open: true 
    tty: true

